### ISSUE TITLE
Remove unused tags

### ISSUE THREAD

**Issue by Lahphim** [akoliyot/nimbl3-dashboard#13]
https://github.com/akoliyot/nimbl3-dashboard/blob/44562d55b7209ff96616c590f7af5d81e1ab2d6f/index.html#L279-L283

I'm not sure that you still use these libraries or not?
I think our web still work without that libraries. 😇

Or maybe you forget to include `bootstrap css` into the project? 🤔

**Comment by Lahphim** [comment]
I'll close this issue because I saw that you include `bootstrap stylesheet` in the main css file. 🤭

**Comment by akoliyot** [comment]
Yeah, I mostly used Bootstrap just for the dropdowns and the table 😄
