### ISSUE TITLE
Remove `font-awesome`

### ISSUE THREAD

**Issue by Lahphim** [akoliyot/nimbl3-dashboard#7]
https://github.com/akoliyot/nimbl3-dashboard/blob/44562d55b7209ff96616c590f7af5d81e1ab2d6f/index.html#L9

https://github.com/akoliyot/nimbl3-dashboard/blob/44562d55b7209ff96616c590f7af5d81e1ab2d6f/index.html#L19

In the code, I see that we use font icon just only one.
What if we remove `font-awesome` out then download and convert that as the local SVG icon?

**Comment by akoliyot** [comment]
I think that's a great suggestion, I added the font-awesome icon to the local svg image sprite and removed the dependency.
